//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingMachine
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendingMachineChangePurse
    {
        public int Id { get; set; }
        public int NominalValue { get; set; }
        public int NumberOfBills { get; set; }
    }
}
